# Generated by Django 5.0.2 on 2024-03-01 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0003_group_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_create',
        ),
        migrations.AddField(
            model_name='product',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 16, 40, 13, 959695, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
