# Generated by Django 5.0.2 on 2024-03-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate', '0004_remove_product_time_create_product_time_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
